services:
  mysqldb-atrasosRafael:
    image: mysql:8.0
    container_name: mysql_atrasosRafael
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "175T10SJ"
      MYSQL_DATABASE: AtrasosRafael
      MYSQL_USER: root

    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kebibara", "-p175T10SJ"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  mysql_data: