services:
  mysqldb-atrasosRafael:
    image: mysql:8.0
    container_name: mysql_atrasosRafael
    restart: always
    environment:
      MYSQL_DATABASE: AtrasosRafael
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p\"25164036Ka!\" || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
